# Minimal working TensorZero configuration based on official quickstart

# Basic chat function with multiple provider variants
[functions.chat]
type = "chat"

# OpenAI variants
[functions.chat.variants.gpt4]
type = "chat_completion"
model = "openai::gpt-4"

[functions.chat.variants.gpt4_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini"

# Anthropic variants (commented out for now - will enable after testing)
# [functions.chat.variants.claude3_opus]
# type = "chat_completion"
# model = "anthropic::claude-3-opus-20240229"

# Simple haiku generation function (from official example)
[functions.generate_haiku]
type = "chat"

[functions.generate_haiku.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini"